
----------------
-- ED TABLES
----------------
ALTER TABLE :schema.SRC_MOD_OBJECTS
ADD CONSTRAINT SRC_MOD_OBJECTS_FK     FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID);

ALTER TABLE :schema.SRC_TRX_OBJECTS
ADD CONSTRAINT SRC_TRX_OBJECTS_FK     FOREIGN KEY (TRX_ID) REFERENCES :schema.SRC_TRANSACTIONS (TRX_ID),
ADD CONSTRAINT SRC_TRX_OBJECTS_FK2    FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID);

ALTER TABLE :schema.SRC_VIOLATIONS
ADD CONSTRAINT SRC_VIOLATIONS_FK     FOREIGN KEY (SNAPSHOT_ID) REFERENCES :schema.DIM_SNAPSHOTS (SNAPSHOT_ID),
ADD CONSTRAINT SRC_VIOLATIONS_FK2    FOREIGN KEY (RULE_ID) REFERENCES :schema.DIM_RULES (RULE_ID),
ADD CONSTRAINT SRC_VIOLATIONS_FK3    FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID); 

ALTER TABLE :schema.SRC_HEALTH_IMPACTS
ADD CONSTRAINT SRC_HEALTH_IMPACTS_FK FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID); 

ALTER TABLE :schema.USR_EXCLUSIONS
ADD CONSTRAINT USR_EXCLUSIONS_FK     FOREIGN KEY (RULE_ID) REFERENCES :schema.DIM_RULES (RULE_ID),
ADD CONSTRAINT USR_EXCLUSIONS_FK2    FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID);

ALTER TABLE :schema.USR_ACTION_PLAN
ADD CONSTRAINT USR_ACTION_PLAN_FK    FOREIGN KEY (RULE_ID) REFERENCES :schema.DIM_RULES (RULE_ID),
ADD CONSTRAINT USR_ACTION_PLAN_FK2   FOREIGN KEY (OBJECT_ID) REFERENCES :schema.SRC_OBJECTS (OBJECT_ID);

