
----------------
-- ED TABLES
----------------
ALTER TABLE SRC_MOD_OBJECTS
ADD CONSTRAINT SRC_MOD_OBJECTS_FK     FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE;

ALTER TABLE SRC_TRX_OBJECTS
ADD CONSTRAINT SRC_TRX_OBJECTS_FK     FOREIGN KEY (TRX_ID) REFERENCES SRC_TRANSACTIONS (TRX_ID) ON DELETE CASCADE,
ADD CONSTRAINT SRC_TRX_OBJECTS_FK2    FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE;

ALTER TABLE SRC_TRX_HEALTH_IMPACTS
ADD CONSTRAINT SRC_TRX_HEALTH_IMPACTS_FK     FOREIGN KEY (TRX_ID) REFERENCES SRC_TRANSACTIONS (TRX_ID) ON DELETE CASCADE,
ADD CONSTRAINT SRC_TRX_HEALTH_IMPACTS_FK2    FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE;

ALTER TABLE SRC_VIOLATIONS
ADD CONSTRAINT SRC_VIOLATIONS_FK     FOREIGN KEY (SNAPSHOT_ID) REFERENCES DIM_SNAPSHOTS (SNAPSHOT_ID) ON DELETE CASCADE,
ADD CONSTRAINT SRC_VIOLATIONS_FK2    FOREIGN KEY (RULE_ID) REFERENCES DIM_RULES (RULE_ID) ON DELETE CASCADE,
ADD CONSTRAINT SRC_VIOLATIONS_FK3    FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE; 

ALTER TABLE SRC_HEALTH_IMPACTS
ADD CONSTRAINT SRC_HEALTH_IMPACTS_FK FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE; 

ALTER TABLE USR_EXCLUSIONS
ADD CONSTRAINT USR_EXCLUSIONS_FK     FOREIGN KEY (RULE_ID) REFERENCES DIM_RULES (RULE_ID) ON DELETE CASCADE,
ADD CONSTRAINT USR_EXCLUSIONS_FK2    FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE;

ALTER TABLE USR_ACTION_PLAN
ADD CONSTRAINT USR_ACTION_PLAN_FK    FOREIGN KEY (RULE_ID) REFERENCES DIM_RULES (RULE_ID) ON DELETE CASCADE,
ADD CONSTRAINT USR_ACTION_PLAN_FK2   FOREIGN KEY (OBJECT_ID) REFERENCES SRC_OBJECTS (OBJECT_ID) ON DELETE CASCADE;

